engines:
  rubocop:
    enabled: true
    AllCops:
      RunRailsCops: true
      Exclude:
        - 'vendor/**/*'
        - 'tmp/**/*'
        - lib/procedo/handler_method.rb
        - lib/working_set/query_language.rb

    Metrics/LineLength:
      Enabled: false