image: "ruby:2.4.0"
services:
  - postgres:latest
  - elasticsearch:latest
variables:
  POSTGRES_DB: dbname
  POSTGRES_USER: username
  POSTGRES_PASSWORD: ""
before_script:
  - apt-get update -qq && apt-get install -y -qq postgresql postgresql-contrib libpq-dev cmake
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - RAILS_ENV=test bundle install --full-index --jobs $(nproc) "${FLAGS[@]}"
  - cp config/database.yml.sample config/database.yml
  - RAILS_ENV=test bundle exec rake db:create db:migrate
test:
  script:
    - bundle exec rake test
