language: ruby
bundler_args: "--full-index --without development"
# cache: bundler
rvm:
- 2.2.7
before_install: test/ci/before_install
before_script: test/ci/before_script
script: xvfb-run bundle exec rake test:models test:libs test:controllers DRIVER=webkit
services:
- redis-server
