targets:
  ubuntu-14.04:
    env:
      - "JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64"
      - "NOKOGIRI_USE_SYSTEM_LIBRARIES=1"
    dependencies:
      - postgresql-9.3-postgis-2.1
      - graphicsmagick
      - tesseract-ocr
      - tesseract-ocr-ara
      - tesseract-ocr-jpn
      - tesseract-ocr-fra
      - tesseract-ocr-eng
      - tesseract-ocr-spa
      - pdftk
      - libreoffice
      - poppler-utils
      - poppler-data
      - ghostscript
      - openjdk-7-jdk
      - libicu52
    build_dependencies:
      - libcurl4-openssl-dev
      - openjdk-7-jdk
      - libgeos-dev
      - libgeos++-dev
      - libproj-dev
      - libpq-dev
      - libxml2-dev 
      - libxslt1-dev
      - zlib1g-dev
      - libicu-dev
services:
  - postgres
