user: ekylibre
group: ekylibre
env:
  - "JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64"
  - "NOKOGIRI_USE_SYSTEM_LIBRARIES=1"
dependencies:
  - graphicsmagick
  - tesseract-ocr
  - tesseract-ocr-ara
  - tesseract-ocr-jpn
  - tesseract-ocr-fra
  - tesseract-ocr-eng
  - tesseract-ocr-spa
  - pdftk
  - libreoffice
  - poppler-utils
  - poppler-data
  - ghostscript
  - openjdk-7-jdk
  - libicu52
  - nginx
build_dependencies:
  - libcurl4-openssl-dev
  - openjdk-7-jdk
  - libgeos-dev
  - libgeos++-dev
  - libproj-dev
  - libpq-dev
  - libxml2-dev 
  - libxslt1-dev
  - zlib1g-dev
  - libicu-dev
targets:
  debian-8:
    dependencies:
      - postgresql-9.4-postgis-2.1
  ubuntu-14.04:
    dependencies:
      - postgresql-9.3-postgis-2.1
services:
  - postgres
before_precompile: "packaging/setup"
after_precompile: "packaging/clean"
after_install: "packaging/postinst"
