AllCops:
  RunRailsCops: true
  Exclude:
    - 'lib/generators/*/templates/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'plugins/**/*'
    - 'plugins-*/**/*'
    - 'lib/procedo/formula/language.rb'
    - 'lib/working_set/query_language.rb'
    - 'db/schema.rb'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 60