# This file contains configuration specific for this repository that are different from the default Ekylibre style guide

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/first_runs/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'lib/generators/**/*'
    - 'node_modules/**/*'
    - 'plugins/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'plugins-disabled/**/*'

# TODO: Enable this on a next Gemfile update
Bundler/OrderedGems:
  Enabled: false

# We disable this for now. 1500 offenses as of 01/02/2021
Layout/LineLength:
  Enabled: false

# Too many offenses to enable this for now.
Style/StringLiterals:
  Enabled: false
