language: ruby
bundler_args: --full-index --without development
cache: bundler
rvm:
  - 2.2.3
env:
  - TEST_SUITE=models
  - TEST_SUITE=controllers
  - TEST_SUITE=helpers
  - TEST_SUITE=integration
  - TEST_SUITE=lib
  - TEST_SUITE=javascripts
before_install: test/ci/before_install
before_script:  test/ci/before_script
script: xvfb-run bundle exec rake test:$TEST_SUITE DRIVER=webkit
services:
  - redis-server