language: ruby
bundler_args: --without 'development doc' --full-index
rvm:
  - 2.0.0
  - 2.1.5
env:
  - TEST_LOCALE=fra
  - TEST_LOCALE=eng
before_install: test/ci/before_install
before_script:  test/ci/before_script
script: xvfb-run bundle exec rake test:run_all DRIVER=webkit LOCALE=$TEST_LOCALE
# script: bundle exec rake test:core
