language: ruby
bundler_args: --without development doc
rvm:
  - 1.9.3
  - 2.0.0
before_install: test/ci/before_install
before_script: test/ci/before_script
script: bundle exec rake test:core
matrix:
  allow_failures:
    - rvm: 2.1.0
addons:
  sauce_connect:
    username: "ekylibre"
    access_key: "ae8ec53f-9fdf-49d0-bdc5-0816bca01132"