rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
env:
  - DB=mysql
  - DB=postgresql
  - DB=sqlite3
before_script: 
  - "ci/setup"
  - "bundle exec rake db:migrate RAILS_ENV= RACK_ENV="
script: "bundle exec rake test"
