rvm:
# - 1.9.2
  - 1.9.3
env:
  - DB=postgis POSTGIS=v15
  - DB=postgis POSTGIS=v20
#  - DB=spatialite

#  - DB=mysql
#  - DB=postgresql
#  - DB=sqlite3
before_install: 
  - test/ci/install
before_script:
  - test/ci/setup
  - bundle exec rake db:migrate
script: bundle exec rake test
