rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
env:
  - DB=mysql
  - DB=postgresql
  - DB=sqlite3
before_script: 
  - "ci/setup"
  - "env -u RAILS_ENV" # Removes RAILS_ENV variable which seems to be set
  - "bundle exec rake db:migrate"
script: "bundle exec rake test"
