postgis:
  image: mdillon/postgis
  volumes:
    - ./tmp/data/postgres/ekylibre:/var/lib/postgresql/data
  ports:
    - "5432:5432"

redis:
  image: redis:3.0
  volumes:
    - /tmp/data/redis/ekylibre:/data
  ports:
    - "6379:6379"
