fr_pcga:
  profit_and_loss_statement:
    products_sales: '707 7097 C'
    animal_sales: '704 7094 756 C'
    productions_sales: '701 702 703 705 706 708 7091 7092 7093 7095 7096 7098 C'
    inventory_variations: '712 713 C'
    capitalised_production: '721 722 724 726 C'
    subsidies: '741 742 743 744 745 C'
    provisions_revenues: '781 791 C'
    other_products: '75 C, !756'
    merchandises_purchases: '607 6097 D'
    merchandises_purchases_stocks_variation: '6037 D'
    products_purchases: '601 602 6091 6092 D'
    purchases_stocks_variation: '6031 6032 D'
    animal_purchases: '604 6094 D'
    other_purchases: '605 606 61 62 6095 6096 6098 656 D'
    taxes: '63 D'
    wages: '64 D, !645 !646 !647 !648'
    social_expenses: '645 646 647 648 D'
    depreciations_inputations_expenses: '681 D'
    other_expenses: '65 D, !656'
    products_subtotal: '70 71 72 74 75 781 791 C'
    charges_subtotal: '60 61 62 63 64 65 681'
    exploitation_result: '70 71 72 74 75 781 791 C, - 60 61 62 63 64 65 681'
    financial_participations: '761 C'
    financial_debts: '762 C'
    financial_others_interests: '763 764 765 768 C'
    financial_depreciations: '786 796 C'
    financial_positive_change: '766 C'
    financial_net_cession_values: '767 C'
    financial_products_subtotal: '76 786 796 C'
    financial_asset_dotations: '686 D'
    financial_interests_and_charges: '661 664 665 668 D'
    financial_negative_change: '666 D'
    financial_net_cession_debts: '667 D'
    financial_expenses_subtotal: '66 686 D'
    financial_result: '76 786 796 C, - 66 686'
    before_taxe_result: '70 71 72 74 75 781 791 76 786 796 C, - 60 61 62 63 64 65 681 66 686'
    exceptional_products_on_management_operations: '771 C'
    exceptional_products_on_assets_cessions: '775 C'
    exceptional_products_on_capital_operations: '777 778 C'
    exceptional_products_on_provisions: '787 797 C'
    exceptional_products_subtotal: '77 787 797 C'
    exceptional_expenses_on_management_operations: '671 673 D'
    exceptional_expenses_on_assets_cessions: '675 D'
    exceptional_expenses_on_capital_operations: '678 D'
    exceptional_expenses_on_provisions: '687 D'
    exceptional_expenses_subtotal: '67 687 D'
    exceptional_result: '77 787 797 C, - 67 687'
    employee_involvement: '691 D'
    profit_taxe: '695 697 699 D'
    products_total: '7 C'
    charges_total: '6 D'
    exercice_result: '70 71 72 74 75 781 791 76 786 796 77 787 797 C, - 60 61 62 63 64 65 681 66 686 67 687 691 695 697 699'
  ratio:
    exercice_production: '70 71 72 73 756 C, !707 !7097'
    commercial_margin: '707 7097 C, - 607 6097 6037'
    production_purchases: '601 602 6091 6092 6031 6032 D'
    production_others_charges: '605 606 61 62 6355 6095 6096 6098 D'
    added_value: '70 71 72 73 756 707 7097 C, - 607 6097 6037 601 602 6091 6092 6031 6032 605 606 61 62 6355 6095 6096 6098'
    taxes_and_wages: '63 64 D, !6355'
    subsidies: '742 743 744 745 C'
    operating_margin: '70 71 72 73 756 707 7097 742 743 744 745 C, - 607 6097 6037 601 602 6091 6092 6031 6032 605 606 61 62 6355 6095 6096 6098 63 64'
  balance_sheet:
    unsubcribed_capital: '109'
    incorporeal_assets_creation_costs: '201'
    incorporeal_assets_creation_costs_depreciations: '2801 C'
    incorporeal_assets_others: '203 205 206 207 208'
    incorporeal_assets_others_depreciations: '2803 2805 2807 2808 2905 2906 2907 2908 C'
    incorporeal_assets_advances: '237'
    incorporeal_assets_total: '109 201 203 205 206 207 208 237'
    incorporeal_assets_total_depreciations: '2801 2803 2805 2807 2808 2905 2906 2907 2908 C'
    corporeal_assets_land_parcels: '211'
    corporeal_assets_land_parcels_depreciations: '2811 2911 C'
    corporeal_assets_settlements: '212'
    corporeal_assets_settlements_depreciations: '2812 2912 C'
    corporeal_assets_enhancement: '217'
    corporeal_assets_enhancement_depreciations: '2817 2917 C'
    corporeal_assets_buildings: '213 214'
    corporeal_assets_buildings_depreciations: '2813 2814 2913 2914 C'
    corporeal_assets_equipments: '215'
    corporeal_assets_equipments_depreciations: '2815 2915 C'
    corporeal_assets_others: '218'
    corporeal_assets_others_depreciations: '2818 2918 C'
    corporeal_assets_in_progress: '231'
    corporeal_assets_in_progress_depreciations: '2931 C'
    corporeal_assets_advances: '2381'
    corporeal_assets_total: '21 231 2381'
    corporeal_assets_total_depreciations: '281 291 2931 C'
    alive_corporeal_assets_adult_animals: '241'
    alive_corporeal_assets_adult_animals_depreciations: '2841 2941 C'
    alive_corporeal_assets_young_animals: '242'
    alive_corporeal_assets_young_animals_depreciations: '2942 C'
    alive_corporeal_assets_service_animals: '243'
    alive_corporeal_assets_service_animals_depreciations: '2843 2943 C'
    alive_corporeal_assets_perennial_plants: '246'
    alive_corporeal_assets_perennial_plants_depreciations: '2846 2946 C'
    alive_corporeal_assets_others: '247'
    alive_corporeal_assets_others_depreciations: '2847 2947 C'
    alive_corporeal_assets_in_progress: '234'
    alive_corporeal_assets_in_progress_depreciations: '2934 C'
    alive_corporeal_assets_advances: '2384'
    alive_corporeal_assets_total: '24 234 2384'
    alive_corporeal_asset_total_depreciations: '284 294 2934 C'
    financial_assets_participations: '261 262 266'
    financial_assets_participations_depreciations: '2961 2962 2966 C'
    financial_assets_participations_debts: '267 268'
    financial_assets_participations_debts_depreciations: '2967 2968 C'
    financial_assets_others: '271 272 274 275 276'
    financial_assets_others_depreciations: '2971 2972 2974 2975 2976 C'
    financial_assets_total: '26 27'
    financial_asset_total_depreciations: '296 297 C'
    long_cycle_alive_products_animals: '31'
    long_cycle_alive_products_animals_depreciations: '391 C'
    long_cycle_alive_products_plant_advance: '331'
    long_cycle_alive_products_plant_advance_depreciations: '3931 C'
    long_cycle_alive_products_plant_in_ground: '332 338'
    long_cycle_alive_products_plant_in_ground_depreciations: '3932 3938 C'
    long_cycle_alive_products_wine: '351 352'
    long_cycle_alive_products_wine_depreciations: '3951 3952 C'
    long_cycle_alive_products_others: '356 357 358'
    long_cycle_alive_products_others_depreciations: '3956 3957 3958 C'
    long_cycle_alive_products_total: '31 33 35'
    long_cycle_alive_products_total_depreciations: '391 393 395 C'
    short_cycle_alive_products_animals: '32'
    short_cycle_alive_products_animals_depreciations: '392 C'
    short_cycle_alive_products_plant_advance: '341'
    short_cycle_alive_products_plant_advance_depreciations: '3941 C'
    short_cycle_alive_products_plant_in_ground: '348'
    short_cycle_alive_products_plant_in_ground_depreciations: '3948 C'
    short_cycle_alive_products_others: '36'
    short_cycle_alive_products_others_depreciations: '396 C'
    short_cycle_alive_products_total: '32 34 36'
    short_cycle_alive_products_total_depreciations: '392 394 396 C'
    stocks_total: '30 37'
    stock_total_depreciations: '390 397 C'
    advance_giveables: '4091'
    client_receivables: '41 !4191 !4196 !4197 !4198'
    client_receivable_provisions: '4916 4912 C'
    state_receivables: '445 D'
    associate_receivables: '455 D, !4553 !4554'
    associate_receivable_provisions: '4955 C'
    other_receivables: '1641 1642 1643 D, 169 4096 4097 4098 425 4287 4387 441 !4419, 443 444 D, 462 465 4487 4687, 451 452 453 454 456 458 461 467 478 D'
    other_receivable_provisions: '495 496 C'
    investment_security: '502 503 504 505 506 507 508'
    investment_security_provisions: '59 C'
    reserve: '511 ,512 514 D ,515 516 ,517 D, 5187 53 54'
    advance_charges: '486 481'
    assets_gaps: '470 471 D, 476'
    capitals: '101 108 C'
    emissions_and_reevaluation_gaps: '104 105 C'
    liability_reserves: '106 C'
    anew_reports: '11 C'
    profit_or_loss: '12 C'
    investment_subsidies: '13 C'
    derogatory_depreciations: '145 C'
    mandatory_provisions: '142 143 144 146 147 148 C'
    risk_and_charges_provisions: '151 153 155 156 157 158 C'
    loans_debts: '1641 1642 1643 C'
    associate_locked_debts: '4553 4554'
    cashe_debts: '519, 512 514 517 C, 5186'
    other_financial_debts: '161 163 165 1675 168 C, 17 426, 451 456 458 C'
    advance_receivables: '4191'
    supplier_receivables: '401 4031 402 4032 408 C'
    state_debts: '445 C'
    social_debts: '421 422 424 427 4282 4284 4286 431 437 4382 4386 442, 443 444 C, 446 447 4482 4486 457'
    associate_debts: '455 C, !4553 !4554'
    fixed_asset_debts: '269 279 404 405 4084'
    other_debts: '4196 4197 4198 4419, 452 453 454 461 467 478 C, 464 4686 509'
    advance_products: '487'
    liabilities_gaps: '470 471 C, 477'
fr_pcg82:
  profit_and_loss_statement:
    products_sales: '707 7097 C'
    services_sales: '701 702 703 7091 7092 C'
    productions_sales: '70 C, !707 !7097 !701 !702 !703 !7091 !7092'
    inventory_variations: '71 C'
    capitalised_production: '72 73 C'
    subsidies: '74 C'
    provisions_revenues: '781 791 C'
    other_products: '751 752 753 758 C'
    merchandises_purchases: '607 6087 6097 D'
    merchandises_purchases_stocks_variation: '6037 D'
    products_purchases: '601 602 6081 6091 6092 D'
    purchases_stocks_variation: '6031 6032 D'
    other_purchases: '604 605 606 61 62 6094 6095 6096 D'
    taxes: '63 D'
    wages: '64 D, !645 !646 !647 !648'
    social_expenses: '645 646 647 648 D'
    depreciations_inputations_expenses: '681 D'
    other_expenses: '65 D, !655'
    products_subtotal: '70 71 72 74 75 781 791 C, !755'
    charges_subtotal: '60 61 62 63 64 65 681 D, !655'
    exploitation_result: '70 71 72 74 75 781 791 C, !755, - 60 61 62 63 64 65 681, !655'
    common_profit: '755 C'
    common_loss: '655 D'
    financial_products: '76 786 796 C'
    financial_expenses: '66 686 D'
    financial_result: '76 786 796 C, - 66 686'
    before_taxe_result: '70 71 72 74 75 781 791 76 786 796 C, - 60 61 62 63 64 65 681 66 686'
    exceptional_products: '77 787 797 C'
    exceptional_expenses: '67 687 D'
    exceptional_result: '77 787 797 C, - 67 687'
    employee_involvement: '691 D'
    profit_taxe: '695 697 D'
    exercice_result: '70 71 72 74 75 781 791 76 786 796 77 787 797 C, - 60 61 62 63 64 65 681 66 686 67 687 691 695 697'
  ratio:
    exercice_production: '70 71 72 73 751 752 753 758 C, !707 !7097'
    commercial_margin: '707 7097 C, - 607 6097 6087'
    production_purchases: '601 602 6081 6091 6092 6031 6032 D'
    production_others_charges: '605 606 61 62 6355 6095 6096 6098 D'
    added_value: '70 71 72 73 751 752 753 758 C, - 607 6097 6087 601 602 6081 6091 6092 6031 6032 605 606 61 62 6355 6095 6096 6098'
    taxes_and_wages: '63 64 D, !6355'
    subsidies: '742 743 744 745 C'
    operating_margin: '70 71 72 73 751 752 753 758 742 743 744 745 C, - 607 6097 6087 601 602 6081 6091 6092 6031 6032 605 606 61 62 6095 6096 6098 63 64'
  balance_sheet:
    unsubcribed_capital: '109'
    incorporeal_assets: '20'
    incorporeal_asset_depreciations: '280 C'
    corporeal_assets: '21 23'
    corporeal_asset_depreciations: '281 C'
    financial_assets: '26 27, !269 !279'
    financial_asset_depreciations: '296 297 C'
    stocks: '30 31 32 33 34 35 36 37 38'
    stock_depreciations: '39 C'
    advance_giveables: '409'
    client_receivables: '41, !419'
    client_receivable_provisions: '49 C, !495 !496 !4955'
    state_receivables: '445 D'
    associate_receivables: '45 D'
    associate_receivable_provisions: '4955 C'
    other_receivables: '164 165 D, 169, 42 D, 431 437 438 D, 441 442 443 444 D, 448 449 D, 460 461 462 465, 467 468 D, 4687, 478'
    other_receivable_provisions: '495 496 C, !4955'
    investment_security: '502 503 504 505 506 507 508'
    investment_security_provisions: '59 C'
    reserve: '51 D, 53 58'
    advance_charges: '486 481'
    assets_gaps: '470 471 D, 476'
    capitals: '101 108 C'
    emissions_and_reevaluation_gaps: '104 105 C'
    liability_reserves: '106 C'
    anew_reports: '11'
    profit_or_loss: '- 12'
    investment_subsidies: '13 C'
    derogatory_depreciations: '145 C'
    mandatory_provisions: '142 143 144 146 147 148 C'
    risk_and_charges_provisions: '151 153 155 156 157 158 C'
    loans_debts: '164 165 C'
    associate_locked_debts: '4553 4554 C'
    cashe_debts: '51 C'
    other_financial_debts: '161 162 163 166 167 168 17 18 C'
    advance_receivables: '419'
    supplier_receivables: '400 401 402 403 404 405 408 C, !4084'
    state_debts: '445 C'
    social_debts: '42 C, 431 437 438 C, 446 447 448 449 C'
    associate_debts: '- 45 C !4553 4554'
    fixed_asset_debts: '269 279, 404 405 4084 C'
    other_debts: '441 442 443 444 C, 449 C, 463 464, 467 468 C, 4686, 509'
    advance_products: '487'
    liabilities_gaps: '470 471 C, 477'
