fr_pcga:
  profit_and_loss_statement:
    products_sales: '707 C 7097 C'
    productions_sales: '70 C !707 C !7097 C'
    inventory_variations: '71 C'
    capitalised_production: '72 C'
    subsidies: '74 C'
    provisions_revenues: '781 C 791 C'
    other_products: '73 C 75 C !756 C'
    merchandises_purchases: '607 D 6097 D'
    merchandises_purchases_stocks_variation: '6037 D'
    products_purchases: '601 D 602 D 6091 D 6092 D'
    purchases_stocks_variation: '6031 D 6032 D'
    animal_purchases: '604 D 6094 D'
    other_purchases: '605 D 606 D 6095 D 6096 D 61 D 62 D 6098 D'
    taxes: '63 D'
    wages: '641 D 644 D'
    social_expenses: '645 D 646 D 647 D 648 D'
    depreciations_inputations_expenses: '681 D'
    other_expenses: '65 D'
    products_subtotal: '70 C 71 C 72 C 73 C 74 C 75 C 781 C 791 C !756 C'
    charges_subtotal: '60 61 62 63 64 65 681'
    financial_products: '76 786 796 C'
    financial_expenses: '66 686 D'
    exceptional_products: '77 787 797 C'
    exceptional_expenses: '67 687 D'
    employee_involvement: '691 D'
    profit_taxe: '695 697 699 D'
  balance_sheet:
    unsubcribed_capital: '109'
    incorporeal_assets: '20 237'
    incorporeal_asset_depreciations: '280 290'
    corporeal_assets: '21 231 2381'
    corporeal_asset_depreciations: '281 291 2931'
    alive_corporeal_assets: '24 234 2384'
    alive_corporeal_asset_depreciations: '284 294 2934'
    financial_assets: '26 27'
    financial_asset_depreciations: '296 297'
    long_cycle_alive_products: '31 33 35'
    long_cycle_alive_product_depreciations: '391 393 395'
    short_cycle_alive_products: '32 34 36'
    short_cycle_alive_product_depreciations: '392 394 396'
    stocks: '30 37'
    stock_depreciations: '390 397'
    advance_giveables: '4091'
    client_receivables: '41 !4191 !4196 !4197 !4198'
    client_receivable_provisions: '4916 4912'
    state_receivables: '445 D'
    associate_receivables: '4551 4552 D'
    associate_receivable_provisions: '4955'
    other_receivables: '4096 4097 4098 425 4287 4387 441 !4419, 443 444 D, 462 465 4487 4687, 451 452 453 454 456 458 461 467 478 D'
    other_receivable_provisions: '495 496'
    investment_security: '502 503 504 505 506 507 508'
    investment_security_provisions: '59'
    reserve: '511 ,512 514 D ,515 516 ,517 D, 5187 53 54'
    advance_charges: '486 481'
    assets_gaps: '476'
    capitals: '- 101 108'
    emissions_and_reevaluation_gaps: '- 104 105'
    liability_reserves: '- 106'
    anew_reports: '- 11'
    profit_or_loss: '- 12'
    investment_subsidies: '- 13'
    derogatory_depreciations: '- 145'
    mandatory_provisions: '- 142 143 144 146 147 148'
    risk_and_charges_provisions: '- 151 153 155 156 157 158'
    loans_debts: '- 1641 1642 1643'
    associate_locked_debts: '- 4553 4554'
    cashe_debts: '- 519, 512 514 517 C, 5186'
    other_financial_debts: '- 161 163 165 1675 168 17 426, 451 456 458 C'
    advance_receivables: '- 4191'
    supplier_receivables: '- 401 4031 402 4032 408'
    state_debts: '- 445 C'
    social_debts: '- 421 422 424 427 4282 4284 4286 431 437 4382 4386 442, 443 444 C, 446 447 4482 4486 457'
    associate_debts: '- 4551 4552 C'
    fixed_asset_debts: '- 269 279 404 405 4084'
    other_debts: '- 4196 4197 4198 4419, 452 453 454 461 467 478 C, 464 4686 509'
    advance_products: '- 487'
    liabilities_gaps: '- 477'
fr_pcg82:
  profit_and_loss_statement:
    products_sales: '707 C 7097 C'
    productions_sales: '70 C !707 C !7097 C'
    inventory_variations: '71 C'
    capitalised_production: '72 C'
    subsidies: '74 C'
    provisions_revenues: '781 C 791 C'
    other_products: '73 C 75 C !756 C'
    merchandises_purchases: '607 D 6097 D'
    merchandises_purchases_stocks_variation: '6037 D'
    products_purchases: '601 D 602 D 6091 D 6092 D'
    purchases_stocks_variation: '6031 D 6032 D'
    animal_purchases: '604 D 6094 D'
    other_purchases: '605 D 606 D 6095 D 6096 D 61 D 62 D 6098 D'
    taxes: '63 D'
    wages: '641 D 644 D'
    social_expenses: '645 D 646 D 647 D 648 D'
    depreciations_inputations_expenses: '681 D'
    other_expenses: '65 D'
    products_subtotal: '70 C 71 C 72 C 73 C 74 C 75 C 781 C 791 C !756 C'
    charges_subtotal: '60 D 61 D 62 D 63 D 64 D 65 D 681 D'
    financial_products: '76 C 786C 796 C'
    financial_expenses: '66 D 686 D'
    exceptional_products: '77 C 787 C 797 C'
    exceptional_expenses: '67 D 687 D'
    employee_involvement: '691 D'
    profit_taxe: '695 D 697 D 699 D'
  balance_sheet:
    unsubcribed_capital: '109'
    incorporeal_assets: '20'
    incorporeal_asset_depreciations: '280'
    corporeal_assets: '21'
    corporeal_asset_depreciations: '281'
    financial_assets: '26 27'
    financial_asset_depreciations: '296 297'
    stocks: '30 31 32 35 37'
    stock_depreciations: '390 391 392 395 397'
    advance_giveables: '4091'
    client_receivables: '41'
    client_receivable_provisions: '49 !495 !496 !4955'
    state_receivables: '445 D'
    associate_receivables: '455 D !4553 !4554'
    associate_receivable_provisions: '4955'
    other_receivables: '443 444 D, 451 452 453 454 456 458 D, 461 462 465 467 D, 4687 D, 478 D'
    other_receivable_provisions: '495 !4955, 496'
    investment_security: '502 503 504 505 506 507 508'
    investment_security_provisions: '59'
    reserve: '51 D, 53 58'
    advance_charges: '486 481'
    assets_gaps: '476'
    capitals: '101 108'
    emissions_and_reevaluation_gaps: '104 105'
    liability_reserves: '106'
    anew_reports: '11'
    profit_or_loss: '12'
    investment_subsidies: '13'
    derogatory_depreciations: '145'
    mandatory_provisions: '142 143 144 146 147 148'
    risk_and_charges_provisions: '151 153 155 156 157 158'
    loans_debts: '164 165'
    associate_locked_debts: '4553 4554'
    cashe_debts: '51 C'
    other_financial_debts: '161 163 165 1675 168 17, 426, 451 456 458 C'
    advance_receivables: '4191'
    supplier_receivables: '401 4031 402 4032 408 !4084'
    state_debts: '445 C'
    social_debts: '421 422 424 425 427 428, 431 437 438, 442, 443 444 C, 446 447 448, 457'
    associate_debts: '455 C'
    fixed_asset_debts: '269 279 404 405 4084'
    other_debts: '4419, 452 453 454 C, 461 462 465 467 C, 464 4686, 4987 C, 478 C, 509'
    advance_products: '487'
    liabilities_gaps: '477'