fr_pcga:
  profit_and_loss_statement:
    products_sales: '707 C 7097 C'
    productions_sales: '70 C !707 C !7097 C'
    inventory_variations: '71 C'
    capitalised_production: '72 C'
    subsidies: '74 C'
    provisions_revenues: '781 C 791 C'
    other_products: '73 C 75 C !756 C'
    merchandises_purchases: '607 D 6097 D'
    merchandises_purchases_stocks_variation: '6037 D'
    products_purchases: '601 D 602 D 6091 D 6092 D'
    purchases_stocks_variation: '6031 D 6032 D'
    animal_purchases: '604 D 6094 D'
    other_purchases: '605 D 606 D 6095 D 6096 D 61 D 62 D 6098 D'
    taxes: '63 D'
    wages: '641 D 644 D'
    social_expenses: '645 D 646 D 647 D 648 D'
    depreciations_inputations_expenses: '681 D'
    other_expenses: '65 D'
    products_subtotal: '70 C 71 C 72 C 73 C 74 C 75 C 781 C 791 C !756 C'
    charges_subtotal: '60 D 61 D 62 D 63 D 64 D 65 D 681 D'
    financial_products: '76 C 786C 796 C'
    financial_expenses: '66 D 686 D'
    exceptional_products: '77 C 787 C 797 C'
    exceptional_expenses: '67 D 687 D'
    employee_involvement: '691 D'
    profit_taxe: '695 D 697 D 699 D'
fr_pcg82:
  profit_and_loss_statement:
    products_sales: '707 C 7097 C'
    productions_sales: '70 C !707 C !7097 C'
    inventory_variations: '71 C'
    capitalised_production: '72 C'
    subsidies: '74 C'
    provisions_revenues: '781 C 791 C'
    other_products: '73 C 75 C !756 C'
    merchandises_purchases: '607 D 6097 D'
    merchandises_purchases_stocks_variation: '6037 D'
    products_purchases: '601 D 602 D 6091 D 6092 D'
    purchases_stocks_variation: '6031 D 6032 D'
    animal_purchases: '604 D 6094 D'
    other_purchases: '605 D 606 D 6095 D 6096 D 61 D 62 D 6098 D'
    taxes: '63 D'
    wages: '641 D 644 D'
    social_expenses: '645 D 646 D 647 D 648 D'
    depreciations_inputations_expenses: '681 D'
    other_expenses: '65 D'
    products_subtotal: '70 C 71 C 72 C 73 C 74 C 75 C 781 C 791 C !756 C'
    charges_subtotal: '60 D 61 D 62 D 63 D 64 D 65 D 681 D'
    financial_products: '76 C 786C 796 C'
    financial_expenses: '66 D 686 D'
    exceptional_products: '77 C 787 C 797 C'
    exceptional_expenses: '67 D 687 D'
    employee_involvement: '691 D'
    profit_taxe: '695 D 697 D 699 D'
