local: &local
  :url: redis://localhost:6379
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true
development: *local
test: &test
  :url: redis://redis:6379/
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true