default: &default
  adapter: postgis
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  max_pool_size: 5
  postgis_extension: []

  # Schema search path. The server defaults to $user,public
  schema_search_path: public, postgis

  # The specified database role being used to connect to postgres.
  # To create additional roles in postgres see `$ createuser --help`.
  # When left blank, postgres will use the default role. This is
  # the same name as the operating system user that initialized the database.
  username: ekylibre

  # The password associated with the postgres role (username).
  password: ekylibre

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  host: 127.0.0.1


db_cluster: &db_cluster
  <<: *default
  host: 46.105.116.55
  username: prod
  password: pwlyc3pondjtcn0unb2rm8
  clustered: true

development:
  <<: *default
  database: ekylibre_development_master

# athena_db_1:
#   <<: *db_cluster
#   database: athena_db_1
#
# athena_db_2:
#   <<: *db_cluster
#   database: athena_db_2
#
# athena_db_3:
#   <<: *db_cluster
#   database: athena_db_3
#
# athena_db_4:
#   <<: *db_cluster
#   database: athena_db_4
#
# athena_db_5:
#   <<: *db_cluster
#   database: athena_db_5
#
# athena_db_6:
#   <<: *db_cluster
#   database: athena_db_6
#
# athena_db_7:
#   <<: *db_cluster
#   database: athena_db_7
#
# athena_db_8:
#   <<: *db_cluster
#   database: athena_db_8
#
# athena_db_9:
#   <<: *db_cluster
#   database: athena_db_9
#
# athena_db_10:
#   <<: *db_cluster
#   database: athena_db_10
#
# athena_db_11:
#   <<: *db_cluster
#   database: athena_db_11
#
# athena_db_12:
#   <<: *db_cluster
#   database: athena_db_12
#
# athena_db_13:
#   <<: *db_cluster
#   database: athena_db_13
#
# athena_db_14:
#   <<: *db_cluster
#   database: athena_db_14
#
# athena_db_15:
#   <<: *db_cluster
#   database: athena_db_15

production:
  <<: *default
  database: ekylibre_production_master
  username: ekylibre
  password: ekylibre

test:
  <<: *default
  database: ekylibre_test_master
  username: ekylibre
  password: ekylibre
