datasources:
  trial-balance:
    action: "backend/financial_years#trial_balance"
    model: "financial_years"
    parameters: id
  general-journal:
    action: "backend/journals#general_journal"
    parameters: all
  sales-estimate:
    action: "backend/sales#show"
    parameters: id
  sales-order:
    action: "backend/sales#show"
    parameters: id
  sales-invoice:
    action: "backend/sales#show"
    parameters: id
