# Accéder au minimum vital
__minimum__:
  actions:
  - application::i18nize
  - authentication::index
  - authentication::login
  - authentication::logout
  - authentication::register
  - company::about
  - company::change_password
  - company::formalize
  - company::help
  - company::index
  - company::side
  - company::tabbox_index
  - company::unknown_action
  - company::user_statistics
  - company::welcome
  - help::close
  - help::previous
  - help::search
  - help::side
  - management::product_trackings
  - management::product_units
# Droit par défaut (inaccessible)
__not_used__:
  actions:
  - accountancy::import
  - resources::employee
  - resources::employee_delete
  - resources::employee_events_dyta
  - resources::employee_sale_orders_dyta
  - resources::employee_shape_operations_dyta
  - resources::employees
  - resources::employees_dyta
  - resources::index
  - resources::profession_create
  - resources::profession_delete
  - resources::profession_update
  - resources::professions
  - resources::professions_dyta
# Accéder au module Comptabilité
administrate_accountancy:
  controller: accountancy
  actions: [accountize, index]
# Accéder au module Commerce
administrate_management:
  controller: management
  actions:
  - account_dyli
  - all_contacts_dyli
  - critic_stocks_dyta
  - entities_dyli
  - index
  - payment_purchase_orders_dyta
  - payment_sale_orders_dyta
  - payments_dyta
  - purchase_order_payment_parts_dyta
  - sale_lines_dyta
  - sale_order_deliveries_dyta
  - sale_order_lines_dyta
  - sale_order_natures_dyta
  - sale_order_payments_dyta
  - sale_orders_dyta
  - subscription_contacts_dyli
  - undelivered_quantities_dyta
  - undelivered_sales_dyta
  - unexecuted_transfers_dyta
  - unpaid_sale_orders_export
  - unvalidated_embankments_dyta
# Accéder au module Production
administrate_production:
  controller: production
  actions: [index]
# Accéder au module Relations clients/fournisseurs
administrate_relations:
  controller: relations
  actions:
  - auto_complete_for_contact_line_6
  - change_minutes
  - entities_dyli
  - index
  - recent_events_dyta
# Effectuer/Recharger des sauvegardes
backup_company:
  controller: company
  actions: [backups]
# Faire des avoirs
cancel_invoices:
  controller: management
  actions: [credit_lines_dyta, invoice_cancel]
# Changer les prix au moment des ventes
change_prices_on_sale:
  controller: management
# Clôturer et déclôturer des journaux
close_journals:
  controller: accountancy
  actions: [journal_close, journal_reopen]
# Configurer les options de la société
configure_company:
  controller: company
  actions:
  - configure
  - sequence_create
  - sequence_delete
  - sequence_update
  - sequences
  - sequences_dyta
  - sequences_load
# Consulter les fiches clients/fournisseurs
consult_entities:
  controller: relations
  actions:
  - entities
  - entities_dyta
  - entity
  - entity_bank_accounts_dyta
  - entity_invoices_dyta
  - entity_payments_dyta
  - entity_sale_orders_dyta
# Consulter les écritures
consult_entries:
  controller: accountancy
# Consulter les écritures
consult_invoices:
  controller: management
  actions: [invoice_credit_lines_dyta, invoice_lines_dyta, invoices_dyta]
# Consulter les prix
consult_prices:
  controller: management
  actions: [prices]
# Consulter les achats
consult_purchases:
  controller: management
  actions:
  - purchase_order
  - purchase_order_lines_dyta
  - purchase_orders
  - purchase_orders_dyta
# Consulter les ventes
consult_sales:
  controller: management
  actions: [sale_order, sale_order_invoices_dyta, sale_orders, statistics]
# Consulter l'état des stocks
consult_stocks:
  controller: management
  actions: [stocks, stocks_dyta]
# Consulter les informations de tracabilité
consult_tracking:
  controller: management
  actions:
  - tracking
  - tracking_operation_lines_dyta
  - tracking_purchase_order_lines_dyta
  - tracking_sale_order_lines_dyta
  - tracking_stocks_dyta
# Créer un devis
create_estimates:
  controller: management
  actions:
  - available_prices_dyli
  - clients_dyli
  - price_find
  - sale_order_contacts
  - sale_order_create
  - sale_order_duplicate
  - sale_order_line_create
  - sale_order_line_delete
  - sale_order_line_informations
  - sale_order_line_stocks
  - sale_order_line_tracking
  - sale_order_line_update
  - sale_order_lines
  - sale_order_subscriptions_dyta
  - sale_order_update
  - subscription_coordinates
  - sum_calculate
# Créer, modifier des achats
create_purchases:
  controller: management
  actions:
  - purchase_order_create
  - purchase_order_delete
  - purchase_order_line_create
  - purchase_order_line_delete
  - purchase_order_line_update
  - purchase_order_lines
  - purchase_order_summary
# Effectuer des extractions (sans pouvoir les concevoir)
extract_listings:
  controller: company
  actions: [listing_extract, listings]
# Octroyer des réductions commerciales lors des ventes
give_discounts_on_sale:
  controller: management
# Importer des données d'autres logiciels
import_data:
  controller: company
  actions: [import]
# Importer, exporter des fiches clients/fournisseurs
import_export_entities:
  controller: relations
  actions: [entities_export, entities_import]
# Gérer l'envoi de courriels
mail_listings:
  controller: company
  actions: [listing_mail, listings]
# Gérer les comptes comptables
manage_accounts:
  controller: accountancy
  actions:
  - account
  - account_children_dyta
  - account_create
  - account_delete
  - account_journal_entries_dyta
  - account_update
  - accounts
  - accounts_dyta
# Gérer les zones
manage_areas:
  controller: relations
  actions: [area_create, area_delete, area_update, areas, areas_dyta]
# Gérer les comptes bancaires
manage_bank_accounts:
  controller: accountancy
  actions:
  - bank_account_create
  - bank_account_delete
  - bank_account_update
  - bank_accounts
  - bank_accounts_dyta
# Gérer les informations de la société
manage_company:
  controller: company
  actions:
  - department_create
  - department_delete
  - department_update
  - departments
  - departments_dyta
  - establishment_create
  - establishment_delete
  - establishment_update
  - establishments
  - establishments_dyta
# Gérer les champs personnalisés
manage_complements:
  controller: relations
  actions:
  - complement
  - complement_choice_create
  - complement_choice_down
  - complement_choice_up
  - complement_choice_update
  - complement_choices_dyta
  - complement_create
  - complement_sort
  - complement_update
  - complements
  - complements_dyta
# Gérer les délais
manage_delays:
  controller: management
  actions:
  - delay
  - delay_create
  - delay_delete
  - delay_update
  - delays
  - delays_dyta
# Gérer les types de livraison
manage_delivery_modes:
  controller: management
  actions:
  - delivery_mode_create
  - delivery_mode_delete
  - delivery_mode_update
  - delivery_modes
  - delivery_modes_dyta
# Gérer les districts
manage_districts:
  controller: relations
  actions:
  - district_create
  - district_delete
  - district_update
  - districts
  - districts_dyli
  - districts_dyta
# Gérer les modèles de document
manage_document_templates:
  controller: company
  actions:
  - document_template_create
  - document_template_delete
  - document_template_duplicate
  - document_template_print
  - document_template_update
  - document_templates
  - document_templates_dyta
  - document_templates_load
# Gérer les remises de chèques
manage_embankments:
  controller: management
  actions:
  - credits_dyta
  - embankable_payments_dyta
  - embankment
  - embankment_create
  - embankment_delete
  - embankment_payments_dyta
  - embankment_update
  - embankments
  - embankments_dyta
  - unvalidated_embankments
# Gérer les fiches clients/fournisseurs
manage_entities:
  controller: relations
  actions:
  - auto_complete_for_entity_origin
  - contact_create
  - contact_delete
  - contact_update
  - contacts_dyta
  - entity_create
  - entity_delete
  - entity_events_dyta
  - entity_purchase_orders_dyta
  - entity_subscriptions_dyta
  - entity_update
# Gérer les types de fiche
manage_entities_natures:
  controller: relations
  actions:
  - entity_nature_create
  - entity_nature_delete
  - entity_nature_update
  - entity_natures
  - entity_natures_dyta
# Gérer les catégories de fiche
manage_entity_categories:
  controller: relations
  actions:
  - category_prices_dyta
  - entity_categories
  - entity_categories_dyta
  - entity_category
  - entity_category_create
  - entity_category_delete
  - entity_category_update
# Gérer les liens entre fiches
manage_entity_links:
  controller: relations
  actions:
  - entity_link_create
  - entity_link_delete
  - entity_link_nature_create
  - entity_link_nature_delete
  - entity_link_nature_update
  - entity_link_natures
  - entity_link_natures_dyta
  - entity_link_update
  - entity_links_dyta
# Gérer les écritures
manage_entries:
  controller: accountancy
  actions:
  - account_dyli
  - account_letter
  - account_unletter
  - journal_entry_create
  - journal_record
  - journal_record_create
  - journal_record_entries_dyta
  - journal_record_update
  - journal_records_dyta
  - lettering
# Gérer les évènements
manage_events:
  controller: relations
  actions:
  - auto_complete_for_event_location
  - event_create
  - event_delete
  - event_nature_create
  - event_nature_delete
  - event_nature_update
  - event_natures
  - event_natures_dyta
  - event_update
  - events
  - events_dyta
# Gérer les exercices
manage_financialyears:
  controller: accountancy
  actions:
  - financialyear
  - financialyear_close
  - financialyear_create
  - financialyear_delete
  - financialyear_update
  - financialyears
  - financialyears_dyta
# Gérer les inventaires
manage_inventories:
  controller: management
  actions:
  - inventories
  - inventories_dyta
  - inventory_create
  - inventory_delete
  - inventory_lines_create_dyta
  - inventory_lines_update_dyta
  - inventory_reflect
  - inventory_update
# Gérer la facturation et les règlements
manage_invoicing:
  controller: management
  actions:
  - payment
  - payment_create
  - payment_delete
  - payment_part_create
  - payment_part_delete
  - payment_update
  - payments
  - sale_order_payment_parts_dyta
  - sale_order_summary
# Gérer les journaux
manage_journals:
  controller: accountancy
  actions:
  - journal
  - journal_create
  - journal_delete
  - journal_update
  - journals
  - journals_dyta
# Gérer les extractions
manage_listings:
  controller: company
  actions:
  - listing_create
  - listing_delete
  - listing_duplicate
  - listing_node_create
  - listing_node_delete
  - listing_node_update
  - listing_update
  - listings
  - listings_dyta
# Gérer les lieux de stockage
manage_locations:
  controller: management
  actions:
  - location
  - location_create
  - location_delete
  - location_stock_moves_dyta
  - location_stocks_dyta
  - location_update
  - locations
  - locations_dyta
# Gérer les responsabilités
manage_mandates:
  controller: relations
  actions:
  - auto_complete_for_mandate
  - auto_complete_for_mandate_family
  - auto_complete_for_mandate_organization
  - auto_complete_for_mandate_title
  - entity_mandates_dyta
  - mandate_create
  - mandate_delete
  - mandate_update
  - mandates
  - mandates_configure
  - mandates_dyta
# Gérer les observations
manage_observations:
  controller: relations
  actions:
  - observation_create
  - observation_delete
  - observation_update
  - observations_dyta
# Gérer les travaux
manage_operations:
  controller: production
  actions:
  - operation
  - operation_create
  - operation_delete
  - operation_line_create
  - operation_lines_dyta
  - operation_nature_create
  - operation_nature_delete
  - operation_nature_update
  - operation_natures
  - operation_natures_dyta
  - operation_products_dyli
  - operation_update
  - operations
  - operations_dyta
  - production::operation_uses_dyta
  - tool_use_create
  - unvalidated_operations
  - unvalidated_operations_dyta
# Gérer les commandes et livraisons
manage_orders:
  controller: management
  actions:
  - deliveries_dyta
  - delivery_contacts_dyli
  - delivery_delete
  - sale_order_confirm
  - sale_order_delete
  - sale_order_deliveries
  - sale_order_delivery_create
  - sale_order_delivery_update
  - sale_order_invoice
  - undelivered_sales
# Gérer les modes de paiments
manage_payment_modes:
  controller: management
  actions:
  - payment_mode_create
  - payment_mode_delete
  - payment_mode_update
  - payment_modes
  - payment_modes_dyta
# Gérer les prix
manage_prices:
  controller: management
  actions:
  - price_create
  - price_delete
  - prices_dyta
  - prices_export
  - prices_import
# Gérer les produits
manage_products:
  controller: management
  actions:
  - change_quantities
  - product_component_create
  - product_component_delete
  - product_component_update
  - product_components_dyta
  - product_create
  - product_delete
  - product_prices_dyta
  - product_stock_moves_dyta
  - product_stocks_dyta
  - product_update
  - products_dyta
# Gérer les types de vente
manage_sale_order_natures:
  controller: management
  actions:
  - sale_order_nature_create
  - sale_order_nature_delete
  - sale_order_nature_update
  - sale_order_natures
# Gérer les îlots
manage_shapes:
  controller: production
  actions:
  - shape
  - shape_create
  - shape_delete
  - shape_operations_dyta
  - shape_update
  - shapes
  - shapes_dyta
# Gérer les catégories de produits
manage_shelves:
  controller: management
  actions:
  - shelf
  - shelf_create
  - shelf_delete
  - shelf_products_dyta
  - shelf_update
  - shelves
  - shelves_dyta
# Pointage des relevés de comptes
manage_statements:
  controller: accountancy
  actions:
  - bank_account_statement
  - bank_account_statement_create
  - bank_account_statement_delete
  - bank_account_statement_entries_dyta
  - bank_account_statement_point
  - bank_account_statement_update
  - bank_account_statements
  - bank_account_statements_dyta
# Gérer les mouvements de stocks
manage_stock_moves:
  controller: management
  actions:
  - stock_move_create
  - stock_move_delete
  - stock_move_update
  - stock_transfer_create
  - stock_transfer_delete
  - stock_transfer_update
  - stock_transfers
  - stock_transfers_dyta
  - unexecuted_transfers
# Gérer les abonnements
manage_subscriptions:
  controller: management
  actions:
  - subscription_coordinates
  - subscription_create
  - subscription_delete
  - subscription_message
  - subscription_nature
  - subscription_nature_create
  - subscription_nature_decrement
  - subscription_nature_delete
  - subscription_nature_increment
  - subscription_nature_update
  - subscription_natures
  - subscription_natures_dyta
  - subscription_update
  - subscriptions
  - subscriptions_dyta
# Gérer les taxes
manage_taxes:
  controller: accountancy
  actions:
  - account_collected_dyli
  - account_paid_dyli
  - tax_create
  - tax_delete
  - tax_update
  - taxes
  - taxes_dyta
# Gérer les outils de production
manage_tools:
  controller: production
  actions:
  - tool
  - tool_create
  - tool_delete
  - tool_operations_dyta
  - tool_update
  - tools
  - tools_dyta
# Gérer les transports
manage_transports:
  controller: management
  actions:
  - deliveries_dyli
  - transport
  - transport_create
  - transport_delete
  - transport_deliveries
  - transport_deliveries_dyta
  - transport_delivery_delete
  - transport_update
  - transports
  - transports_dyta
# Gérer les unités de mesure
manage_units:
  controller: company
  actions:
  - unit_create
  - unit_delete
  - unit_update
  - units
  - units_dyta
  - units_load
# Gérer les utilisateurs
manage_users:
  controller: company
  actions:
  - role_create
  - role_delete
  - role_update
  - roles
  - roles_dyta
  - user
  - user_create
  - user_delete
  - user_lock
  - user_unlock
  - user_update
  - users
  - users_dyta
# Fusionner les fiches clients/fournisseurs
merge_entities:
  controller: relations
  actions: [entities_merge]
# Imprimer
print:
  controller: company
  actions: [print]
# Imprimer les documents comptables
print_accounting_document:
  controller: accountancy
  actions: [document_print]
# Rechercher et consulter des factures
search_and_consult_invoices:
  controller: management
  actions: [invoice, invoices]
# Rechercher et consulter des produits
search_and_consult_products:
  controller: management
  actions: [product, products]
