# Access to the minimum
__minimum__:
  actions:
  - application::i18nize
  - authentication::index
  - authentication::login
  - authentication::logout
  - authentication::register
  - authentication::relogin
  - company::about
  - company::change_password
  - company::formalize
  - company::help
  - company::index
  - company::side
  - company::tabbox_index
  - company::unknown_action
  - company::user_statistics
  - company::welcome
  - help::close
  - help::previous
  - help::search
  - help::side
  - management::account_dyli
  - management::all_contacts_dyli
  - management::client_contacts_dyli
  - management::entities_dyli
  - management::product_trackings
  - management::product_units
  - management::subscription_contacts_dyli
  - production::land_parcels_map
  - relations::entities_dyli
  - relations::recent_events_dyta
  - relations::user_future_events_dyta
  - store::index
# Inaccessible
__not_used__:
  actions:
  - resources::employee
  - resources::employee_delete
  - resources::employee_events_dyta
  - resources::employee_land_parcel_operations_dyta
  - resources::employee_sale_orders_dyta
  - resources::employees
  - resources::employees_dyta
  - resources::index
  - resources::profession_create
  - resources::profession_delete
  - resources::profession_update
  - resources::professions
  - resources::professions_dyta
# Transfer commercial data in accountancy
accountize:
  controller: accountancy
  actions: [accountize, index]
# Make and reload backups
backup_company:
  controller: company
  actions: [backups, index]
# (((BUILD_PRODUCTION_CHAINS)))
build_production_chains:
  controller: production
  actions:
  - index
  - production_chain
  - production_chain_conveyor_create
  - production_chain_conveyor_delete
  - production_chain_conveyor_update
  - production_chain_conveyors_dyta
  - production_chain_create
  - production_chain_delete
  - production_chain_operation
  - production_chain_operation_create
  - production_chain_operation_delete
  - production_chain_operation_down
  - production_chain_operation_up
  - production_chain_operation_update
  - production_chain_operations_dyta
  - production_chain_update
  - production_chains
  - production_chains_dyta
# Cancel invoices
cancel_invoices:
  controller: management
  actions: [credit_lines_dyta, index, invoice_cancel, invoices]
# Change prices on sales
change_prices_on_sale:
  controller: management
# Close and reopen journals
close_journals:
  controller: accountancy
  actions: [index, journal_close, journal_reopen, journals]
# Configure the options of the company
configure_company:
  controller: company
  actions:
  - configure
  - department_create
  - department_delete
  - department_update
  - departments
  - departments_dyta
  - establishment_create
  - establishment_delete
  - establishment_update
  - establishments
  - establishments_dyta
  - index
  - sequence_create
  - sequence_delete
  - sequence_update
  - sequences
  - sequences_dyta
  - sequences_load
# Consult accounting documents
consult_accounting_documents:
  controller: accountancy
  actions: [balance, document_print, general_ledger, general_ledger_dyta, index]
# Consult the people
consult_entities:
  controller: relations
  actions:
  - entities
  - entities_dyta
  - entity
  - entity_cashes_dyta
  - entity_contacts_dyta
  - entity_events_dyta
  - entity_invoices_dyta
  - entity_purchase_orders_dyta
  - entity_purchase_payments_dyta
  - entity_sale_orders_dyta
  - entity_sale_payments_dyta
  - entity_subscriptions_dyta
  - index
# Consult the journal entries
consult_entries:
  controller: accountancy
  actions: [index, journal, journals]
# Consult the invoices
consult_invoices:
  controller: management
  actions:
  - index
  - invoice
  - invoice_credits_dyta
  - invoice_lines_dyta
  - invoices
  - invoices_dyta
# Consult the prices
consult_prices:
  controller: management
  actions: [index, prices]
# Consult the products
consult_products:
  controller: management
  actions: [index, product, products]
# Consult the purchases
consult_purchases:
  controller: management
  actions:
  - index
  - purchase_order
  - purchase_order_lines_dyta
  - purchase_orders
  - purchase_orders_dyta
# Consult the sales
consult_sale_orders:
  controller: management
  actions:
  - index
  - sale_order
  - sale_order_deliveries_dyta
  - sale_order_invoices_dyta
  - sale_order_lines_dyta
  - sale_order_payments_dyta
  - sale_orders
  - sale_orders_dyta
  - statistics
  - unpaid_sale_orders_export
# Consult the stocks
consult_stocks:
  controller: management
  actions: [critic_stocks_dyta, index, stocks, stocks_dyta]
# Consult the tracking informations
consult_tracking:
  controller: management
  actions:
  - index
  - tracking
  - tracking_operation_lines_dyta
  - tracking_purchase_order_lines_dyta
  - tracking_sale_order_lines_dyta
  - tracking_stocks_dyta
# Export listings
extract_listings:
  controller: company
  actions: [index, listing_extract, listings]
# Set reduction on sales
give_discounts_on_sale:
  controller: management
# Import data from other software
import_data:
  controller: company
  actions: [import, index]
# Import, export people listings
import_export_entities:
  controller: relations
  actions: [entities, entities_dyta, entities_export, entities_import, index]
# Send mail to lists
mail_to_listings:
  controller: company
  actions: [index, listing_mail, listings]
# Manage accounts
manage_accounts:
  controller: accountancy
  actions:
  - account
  - account_create
  - account_delete
  - account_entities_dyta
  - account_journal_entry_lines_dyta
  - account_update
  - accounts
  - accounts_dyta
  - accounts_load
  - index
# Manage areas
manage_areas:
  controller: relations
  actions: [area_create, area_delete, area_update, areas, areas_dyta, index]
# Point bank statements
manage_bank_statements:
  controller: accountancy
  actions:
  - bank_statement
  - bank_statement_create
  - bank_statement_delete
  - bank_statement_entries_dyta
  - bank_statement_point
  - bank_statement_update
  - bank_statements
  - bank_statements_dyta
  - index
# Manage cashes
manage_cashes:
  controller: accountancy
  actions:
  - cash
  - cash_bank_statements_dyta
  - cash_create
  - cash_delete
  - cash_deposits_dyta
  - cash_update
  - cashes
  - cashes_dyta
  - index
# Manage custom fields
manage_custom_fields:
  controller: relations
  actions:
  - custom_field
  - custom_field_choice_create
  - custom_field_choice_down
  - custom_field_choice_up
  - custom_field_choice_update
  - custom_field_choices_dyta
  - custom_field_create
  - custom_field_sort
  - custom_field_update
  - custom_fields
  - custom_fields_dyta
  - index
# Manage delays
manage_delays:
  controller: management
  actions:
  - delay
  - delay_create
  - delay_delete
  - delay_update
  - delays
  - delays_dyta
  - index
# Manage deposits
manage_deposits:
  controller: management
  actions:
  - deposit
  - deposit_create
  - deposit_delete
  - deposit_payments_dyta
  - deposit_update
  - depositable_payments_dyta
  - deposits
  - deposits_dyta
  - index
  - unvalidated_deposits
  - unvalidated_deposits_dyta
# Manage districts
manage_districts:
  controller: relations
  actions:
  - district_create
  - district_delete
  - district_update
  - districts
  - districts_dyli
  - districts_dyta
  - index
# Manage document templates
manage_document_templates:
  controller: company
  actions:
  - document_template_create
  - document_template_delete
  - document_template_duplicate
  - document_template_print
  - document_template_update
  - document_templates
  - document_templates_dyta
  - document_templates_load
  - index
# Manage people
manage_entities:
  controller: relations
  actions:
  - auto_complete_for_contact_line_6
  - auto_complete_for_entity_origin
  - contact_create
  - contact_delete
  - contact_update
  - entity_cashes_dyta
  - entity_contacts_dyta
  - entity_create
  - entity_delete
  - entity_events_dyta
  - entity_invoices_dyta
  - entity_mandates_dyta
  - entity_purchase_orders_dyta
  - entity_sale_orders_dyta
  - entity_sale_payments_dyta
  - entity_subscriptions_dyta
  - entity_update
  - index
# Manage people natures
manage_entities_natures:
  controller: relations
  actions:
  - entity_nature_create
  - entity_nature_delete
  - entity_nature_update
  - entity_natures
  - entity_natures_dyta
  - index
# Manage people categories
manage_entity_categories:
  controller: relations
  actions:
  - category_prices_dyta
  - entity_categories
  - entity_categories_dyta
  - entity_category
  - entity_category_create
  - entity_category_delete
  - entity_category_update
  - index
# Manage people links
manage_entity_links:
  controller: relations
  actions:
  - entity_link_create
  - entity_link_delete
  - entity_link_nature_create
  - entity_link_nature_delete
  - entity_link_nature_update
  - entity_link_natures
  - entity_link_natures_dyta
  - entity_link_update
  - entity_links_dyta
  - index
# Create and update estimates
manage_estimates:
  controller: management
  actions:
  - available_prices_dyli
  - clients_dyli
  - index
  - price_find
  - sale_order_contacts
  - sale_order_create
  - sale_order_duplicate
  - sale_order_line_create
  - sale_order_line_delete
  - sale_order_line_detail
  - sale_order_line_informations
  - sale_order_line_stocks
  - sale_order_line_tracking
  - sale_order_line_update
  - sale_order_lines
  - sale_order_subscriptions_dyta
  - sale_order_update
  - subscription_coordinates
  - sum_calculate
# Manage events
manage_events:
  controller: relations
  actions:
  - auto_complete_for_event_location
  - change_minutes
  - event_create
  - event_delete
  - event_nature_create
  - event_nature_delete
  - event_nature_update
  - event_natures
  - event_natures_dyta
  - event_update
  - events
  - events_dyta
  - index
# Manage and close financial years
manage_financial_years:
  controller: accountancy
  actions:
  - financial_year
  - financial_year_close
  - financial_year_create
  - financial_year_delete
  - financial_year_update
  - financial_years
  - financial_years_dyta
  - index
# Manage inventories
manage_inventories:
  controller: management
  actions:
  - index
  - inventories
  - inventories_dyta
  - inventory_create
  - inventory_delete
  - inventory_lines_create_dyta
  - inventory_lines_update_dyta
  - inventory_reflect
  - inventory_update
# Manaeg journal entries
manage_journal_entries:
  controller: accountancy
  actions:
  - account_dyli
  - account_letter
  - account_unletter
  - draft_entry_lines
  - draft_entry_lines_dyta
  - index
  - journal
  - journal_draft_entry_lines_dyta
  - journal_entries_dyta
  - journal_entry
  - journal_entry_create
  - journal_entry_delete
  - journal_entry_entries_dyta
  - journal_entry_line_create
  - journal_entry_lines_dyta
  - journal_entry_update
  - journal_mixed_dyta
  - journals
  - journals_dyta
  - lettering
  - unlettered_journal_entry_lines_dyta
# Manage, close and reopen journals
manage_journals:
  controller: accountancy
  actions:
  - index
  - journal
  - journal_close
  - journal_create
  - journal_delete
  - journal_reopen
  - journal_update
  - journals
  - journals_dyta
# (((MANAGE_LAND_PARCEL_GROUPS)))
manage_land_parcel_groups:
  controller: production
  actions:
  - index
  - land_parcel_group_create
  - land_parcel_group_delete
  - land_parcel_group_update
  - land_parcel_groups
  - land_parcel_groups_dyta
# Manage fields
manage_land_parcels:
  controller: production
  actions:
  - index
  - land_parcel
  - land_parcel_create
  - land_parcel_delete
  - land_parcel_divide
  - land_parcel_operations_dyta
  - land_parcel_update
  - land_parcels
  - land_parcels_dyta
# Manage listings
manage_listings:
  controller: company
  actions:
  - index
  - listing_create
  - listing_delete
  - listing_duplicate
  - listing_node_create
  - listing_node_delete
  - listing_node_update
  - listing_update
  - listings
  - listings_dyta
# Manage mandates
manage_mandates:
  controller: relations
  actions:
  - auto_complete_for_mandate
  - auto_complete_for_mandate_family
  - auto_complete_for_mandate_organization
  - auto_complete_for_mandate_title
  - index
  - mandate_create
  - mandate_delete
  - mandate_update
  - mandates
  - mandates_configure
  - mandates_dyta
# Manage observations
manage_observations:
  controller: relations
  actions:
  - entity_observations_dyta
  - index
  - observation_create
  - observation_delete
  - observation_update
# Manage tasks
manage_operations:
  controller: production
  actions:
  - index
  - operation
  - operation_create
  - operation_delete
  - operation_line_create
  - operation_lines_dyta
  - operation_nature_create
  - operation_nature_delete
  - operation_nature_update
  - operation_natures
  - operation_natures_dyta
  - operation_products_dyli
  - operation_update
  - operation_use_create
  - operation_uses_dyta
  - operations
  - operations_dyta
  - unvalidated_operations
  - unvalidated_operations_dyta
# Manage payment modes
manage_payment_modes:
  controller: management
  actions:
  - index
  - purchase_payment_mode_create
  - purchase_payment_mode_delete
  - purchase_payment_mode_update
  - purchase_payment_modes
  - purchase_payment_modes_dyta
  - sale_payment_mode_create
  - sale_payment_mode_delete
  - sale_payment_mode_update
  - sale_payment_modes
  - sale_payment_modes_dyta
# Manage prices
manage_prices:
  controller: management
  actions:
  - index
  - price_create
  - price_delete
  - price_update
  - prices_dyta
  - prices_export
  - prices_import
# Manage product categories
manage_product_categories:
  controller: management
  actions:
  - index
  - product_categories
  - product_categories_dyta
  - product_category
  - product_category_create
  - product_category_delete
  - product_category_products_dyta
  - product_category_update
# Manage products
manage_products:
  controller: management
  actions:
  - change_quantities
  - index
  - product_component_create
  - product_component_delete
  - product_component_update
  - product_components_dyta
  - product_create
  - product_delete
  - product_prices_dyta
  - product_stock_moves_dyta
  - product_stocks_dyta
  - product_update
  - products_dyta
# Manage purchase orders
manage_purchases:
  controller: management
  actions:
  - index
  - purchase_order_create
  - purchase_order_delete
  - purchase_order_line_create
  - purchase_order_line_delete
  - purchase_order_line_update
  - purchase_order_lines
  - purchase_order_payment_parts_dyta
  - purchase_order_summary
  - purchase_order_update
  - purchase_orders
  - purchase_payment
  - purchase_payment_create
  - purchase_payment_delete
  - purchase_payment_part_create
  - purchase_payment_part_delete
  - purchase_payment_purchase_orders_dyta
  - purchase_payment_update
  - purchase_payments
  - purchase_payments_dyta
  - purchase_products_dyli
  - suppliers_dyli
# Manage sale delivery modes
manage_sale_delivery_modes:
  controller: management
  actions:
  - index
  - sale_delivery_mode_create
  - sale_delivery_mode_delete
  - sale_delivery_mode_update
  - sale_delivery_modes
  - sale_delivery_modes_dyta
# Mange sale orders natures
manage_sale_order_natures:
  controller: management
  actions:
  - index
  - sale_order_nature_create
  - sale_order_nature_delete
  - sale_order_nature_update
  - sale_order_natures
  - sale_order_natures_dyta
# Manages sale orders
manage_sale_orders:
  controller: management
  actions:
  - delivery_contacts_dyli
  - index
  - sale_delivery_create
  - sale_delivery_delete
  - sale_delivery_update
  - sale_order_confirm
  - sale_order_delete
  - sale_order_deliveries
  - sale_order_deliveries_dyta
  - sale_order_invoice
  - undelivered_quantities_dyta
  - undelivered_sales
  - undelivered_sales_dyta
# Manage sale payments
manage_sale_payments:
  controller: management
  actions:
  - index
  - sale_order_payment_parts_dyta
  - sale_order_summary
  - sale_payment
  - sale_payment_create
  - sale_payment_delete
  - sale_payment_part_create
  - sale_payment_part_delete
  - sale_payment_sale_orders_dyta
  - sale_payment_update
  - sale_payments
  - sale_payments_dyta
# Manage stock moves
manage_stock_moves:
  controller: management
  actions:
  - index
  - stock_move_create
  - stock_move_delete
  - stock_move_update
  - stock_transfer_create
  - stock_transfer_delete
  - stock_transfer_update
  - stock_transfers
  - stock_transfers_dyta
  - unexecuted_transfers
  - unexecuted_transfers_dyta
# Manage subscriptions
manage_subscriptions:
  controller: management
  actions:
  - index
  - subscription_coordinates
  - subscription_create
  - subscription_delete
  - subscription_message
  - subscription_nature
  - subscription_nature_create
  - subscription_nature_decrement
  - subscription_nature_delete
  - subscription_nature_increment
  - subscription_nature_update
  - subscription_natures
  - subscription_natures_dyta
  - subscription_update
  - subscriptions
  - subscriptions_dyta
# Manage taxes
manage_taxes:
  controller: accountancy
  actions:
  - collected_account_dyli
  - index
  - paid_account_dyli
  - tax_create
  - tax_delete
  - tax_update
  - taxes
  - taxes_dyta
# Manage tools of production
manage_tools:
  controller: production
  actions:
  - index
  - tool
  - tool_create
  - tool_delete
  - tool_operations_dyta
  - tool_update
  - tools
  - tools_dyta
# Manage transports
manage_transports:
  controller: management
  actions:
  - index
  - sale_deliveries_dyli
  - transport
  - transport_create
  - transport_delete
  - transport_deliveries
  - transport_deliveries_dyta
  - transport_delivery_delete
  - transport_update
  - transports
  - transports_dyta
# Manage units of measure
manage_units:
  controller: company
  actions:
  - index
  - unit_create
  - unit_delete
  - unit_update
  - units
  - units_dyta
  - units_load
# Manage users
manage_users:
  controller: company
  actions:
  - index
  - role_create
  - role_delete
  - role_update
  - roles
  - roles_dyta
  - user
  - user_create
  - user_delete
  - user_lock
  - user_unlock
  - user_update
  - users
  - users_dyta
# Manage warehouses
manage_warehouses:
  controller: management
  actions:
  - index
  - warehouse
  - warehouse_create
  - warehouse_delete
  - warehouse_stock_moves_dyta
  - warehouse_stocks_dyta
  - warehouse_update
  - warehouses
  - warehouses_dyta
# Merge people
merge_entities:
  controller: relations
  actions: [entities, entities_merge, index]
# Print
print:
  controller: company
  actions: [print]
# (((USE_PRODUCTION_CHAINS)))
use_production_chains:
  controller: production
  actions:
  - index
  - production_chain_operation_play
  - production_chains
  - production_chains_dyta
